---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Parameters:
  LineChannelAccessToken:
    Type: String
    Description: LINE のアクセストークン
  LineChannelSecret:
    Type: String
    Description: LINE のチャンネルシークレット
Metadata:
  AWS::ServerlessRepo::Application:
    Name: LINEBotApp
    Description: LINEBot with Amazon Rekognition
    Author: Shoki
    HomePageUrl: https://github.com/irohaonline/ai_linebot
    SourceCodeUrl: https://github.com/irohaonline/ai_linebot
Resources:
  EndPointFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      CodeUri: src
      Handler: mylinebot.lambda_handler
      Environment:
        Variables:
          LINE_CHANNEL_ACCESS_TOKEN:
            Ref: LineChannelAccessToken
          LINE_CHANNEL_SECRET:
            Ref: LineChannelSecret
      Policies:
        RekognitionDetectOnlyPolicy: {}
      Events:
        API:
          Type: Api
          Properties:
            Path: "/api_endpoint"
            Method: post
Outputs:
  ApiEndpointURL:
    Description: API Endpoint URL
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApi.Stage}/api_endpoint
